UPDATE public.roles
SET menu_privileges = ARRAY[
  'View Dashboard',
  'View Project Accounts',
  'Manage Projects',
  'View Petty Cash',
  'Manage Petty Cash',
  'View Pledges',
  'Manage Pledges',
  'View Income',
  'Manage Income',
  'View Expenditure',
  'Manage Expenditure',
  'View Sales Management',
  'View Stocks',
  'Manage Stocks',
  'View Daily Sales',
  'Manage Daily Sales',
  'View Debts',
  'Manage Debts',
  'View Members',
  'Manage Members',
  'Export Member List PDF',
  'Export Member List Excel',
  'View Board Members',
  'Manage Board Members',
  'View Reports',
  'View Member Contributions Report',
  'View Petty Cash Report',
  'View Pledge Report',
  'View Table Banking Summary',
  'View User Activity Report',
  'View Deleted Projects Report',
  'Manage Reports Templates',
  'Perform Admin Actions',
  'Initialize Balances',
  'View My Contributions',
  'Access Admin Settings',
  'Manage User Profiles',
  'Manage User Roles',
  'Manage App Customization',
  'Manage System Currency',
  'Manage Member Fields',
  'Manage Database Maintenance',
  'Manage Financial Accounts',
  'Manage Header Customization'
]
WHERE name = 'Super Admin';