// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dapjsetbprbavmvvifcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcGpzZXRicHJiYXZtdnZpZmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwNTI2NjAsImV4cCI6MjA4MDYyODY2MH0.PIypDoh4Bk-ylXqajUdo_rAeUYkGXxB_QR8CuMIcbEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);