// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Load Supabase configuration from environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Ensure environment variables are set for production builds
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // In a real application, you might want to log this more robustly or
  // display a user-friendly error page.
  throw new Error(
    "Supabase URL and/or Publishable Key are not set. " +
    "Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY " +
    "are defined in your environment variables (e.g., in a .env file)."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);